---
- name: "Install vim"
  apt: pkg=vim install_recommends=no

- name: "Create vim directories"
  file: path={{ item }} state=directory
  with_items:
  - /etc/skel/.vim/autoload
  - /etc/skel/.vim/bundle
  - /root/.vim/autoload
  - /root/.vim/bundle

- name: Copy vimfiles
  copy: src=vimfiles dest={{ item }}
  with_items:
  - /etc/skel/.vim/
  - /root/.vim/

- name: Open swp and backup config access
  file:
    path={{ item }}
    state=directory
    owner=root
    group=root
    mode=0777
    recurse=yes
  with_items:
  - /etc/skel/.vim/swp
  - /etc/skel/.vim/backup
  - /root/.vim/swp
  - /root/.vim/backup

- name: "Download pathogen"
  get_url:
    url="https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim"
    dest=/tmp/pathogen.vim

- name: "Install pathogen"
  copy: src=/tmp/pathogen.vim dest={{ item }}
  with_items:
  - /etc/skel/.vim/autoload/pathogen.vim
  - /root/.vim/autoload/pathogen.vim

- name: Checkout vim plugins
  git: repo={{ item.repo }} dest=/tmp/bundle/{{ item.name }}
  with_items:
  - { repo: "https://github.com/tomtom/tlib_vim.git", name: tlib }
  - { repo: "https://github.com/MarcWeber/vim-addon-mw-utils.git",
      name: vim-addon-mw-utils }
  - { repo: "https://github.com/garbas/vim-snipmate.git",
      name: vim-snipmate }
  - { repo: "https://github.com/altercation/vim-colors-solarized.git",
      name: vim-colors-solarized }
  - { repo: "https://github.com/tpope/vim-sensible.git",
      name: vim-sensible }
  - { repo: "https://github.com/kien/ctrlp.vim.git", name: ctrlp }
  - { repo: "https://github.com/edsono/vim-matchit.git", name: matchit }
  - { repo: "https://github.com/scrooloose/nerdtree.git", name: nerdtree }
  - { repo: "https://github.com/tpope/vim-unimpaired.git",
      name: vim-unimpaired } 
  - { repo: "https://github.com/scrooloose/syntastic.git", name: syntastic }
  - { repo: "https://github.com/ynkdir/vim-vimlparser.git", name: vimparser }
  - { repo: "https://github.com/syngan/vim-vimlint.git", name: vimlint }

- name: Install vim plugins
  copy: src=/tmp/bundle dest={{ item }}
  with_items:
  - /etc/skel/.vim/
  - /root/.vim/

- name: "Copy vimrc.local"
  copy:
    src=vimrc.local dest=/etc/vim/vimrc.local owner=root group=root mode=0644

