---
- name: "Install vim"
  apt: pkg=vim install_recommends=no

- name: "Create vim directories"
  file: path={{ item }} state=directory
  with_items:
  - /etc/skel/.vim/autoload
  - /etc/skel/.vim/bundle
  - /root/.vim/autoload
  - /root/.vim/bundle

- name: "Create vim modifiable directories"
  file: path={{ item }} state=directory mode=0777
  with_items:
  - /etc/skel/.vim/autoload
  - /etc/skel/.vim/bundle
  - /etc/skel/.vim/backup
  - /etc/skel/.vim/swp
  - /root/.vim/autoload
  - /root/.vim/bundle
  - /root/.vim/backup
  - /root/.vim/swp

- name: "Download pathogen"
  get_url:
    url="https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim"
    dest=/tmp/pathogen.vim

- name: "Install pathogen"
  copy: src=/tmp/pathogen.vim dest={{ item }}
  with_items:
  - /etc/skel/.vim/autoload/pathogen.vim
  - /root/.vim/autoload/pathogen.vim

- name: Checkout vim plugins
  git: repo={{ item.repo }} dest=/tmp/bundle/{{ item.name }}
  with_items:
  - { repo: "https://github.com/altercation/vim-colors-solarized.git",
      name: vim-colors-solarized }
  - { repo: "https://github.com/tpope/vim-sensible.git",
      name: vim-sensible }
  - { repo: "https://github.com/kien/ctrlp.vim.git", name: ctrlp }
  - { repo: "https://github.com/edsono/vim-matchit.git", name: matchit }
  - { repo: "https://github.com/scrooloose/nerdtree.git", name: nerdtree }
  - { repo: "https://github.com/tpope/vim-unimpaired.git",
      name: vim-unimpaired } 

- name: Install vim plugins
  copy: src=/tmp/bundle dest={{ item }}
  with_items:
  - /etc/skel/.vim/
  - /root/.vim/
  
- name: "Copy vimrc.local"
  copy: src=vimrc.local dest=/etc/vim/vimrc.local owner=root group=root mode=0644

