---
- name: "Install vim"
  apt: pkg=vim install_recommends=no
  
- name: "Copy vimrc.local"
  copy: src=vimrc.local dest=/etc/vim/vimrc.local owner=root group=root mode=0644

- name: "Set vim as EDITOR"
  lineinfile: dest=/etc/skel/.bashrc line="export EDITOR=vim"
