---
- name: "Install vim"
  apt: pkg=vim install_recommends=no

- name: "Create vim directories"
  file: path={{ item }} state=directory
  with_items:
  - /etc/skel/.vim/autoload
  - /etc/skel/.vim/bundle
  - /root/.vim/autoload
  - /root/.vim/bundle

- name: "Download pathogen"
  get_url:
    url="https://raw.github.com/tpope/vim-pathogen/master/autoload/pathogen.vim"
    dest=/tmp/pathogen.vim

- name: "Install pathogen"
  copy: src=/tmp/pathogen.vim dest={{ item }}
  with_items:
  - /etc/skel/.vim/autoload/pathogen.vim
  - /root/.vim/autoload/pathogen.vim

- name: Checkout vim plugins
  git: repo={{ item.repo }} dest=/tmp/bundle/{{ item.name }}
  with_items:
  - { repo: "git://github.com/altercation/vim-colors-solarized.git", name: vim-colors-solarized }
  - { repo: "git://github.com/tpope/vim-sensible.git", name: vim-sensible }

- name: Install vim plugins
  copy: src=/tmp/bundle dest={{ item }}
  with_items:
  - /etc/skel/.vim/
  - /root/.vim/
  
- name: "Copy vimrc.local"
  copy: src=vimrc.local dest=/etc/vim/vimrc.local owner=root group=root mode=0644

- name: "Set vim as EDITOR"
  lineinfile: dest={{ item }} line="export EDITOR=vim"
  with_items:
  - /etc/skel/.bashrc
  - /root/.bashrc
