---
- name: Install box-store-client
  apt: pkg={{ item }} install_recommends=no
  with_items:
    - cifs-utils

- name: Copy serf mounting script
  copy: src={{ item }} dest=/etc/serf/event_handler.d owner=serf group=serf mode=0755
  with_items:
  - 40-mount_stores.hs

- name: Update serf sudo permissions
  lineinfile: >
    dest=/etc/sudoers.d/serf
    line="serf ALL=(root) NOPASSWD: /sbin/mount.cifs /sbin/umount.cifs"

