---
- hosts: all
  roles:
  - { role: box-common, hostname: BoxCifsStore }
  - box-store
  - box-cifs-store
  tasks:
  - name: Install BoxCifsStore
    apt: pkg={{ item }} install_recommends=no
    with_items:
    - cifs-utils



