---
- hosts: all
  roles:
  - { role: box-common, hostname: BoxCifsStore }
  - serf
  - box-store
  tasks:
  - name: Install BoxCifsStore
    apt: pkg={{ item }} install_recommends=no
    with_items:
    - cifs-utils

  - name: Create box mount directory
    file: path=/mnt/box state=directory

  - name: Add CIFS share to fstab
    lineinfile:
      insertafter=EOF
      line="//10.0.2.2/box /mnt/box cifs noauto,credentials=/etc/samba/box.cifs.credentials"
      dest=/etc/fstab

  - name: Add export directory to fstab
    lineinfile:
      insertafter=EOF
      line="/mnt/box /srv/samba/share noauto bind 0 0"
      dest=/etc/fstab




