---
- name: Download serf
  get_url:
    url=https://dl.bintray.com/mitchellh/serf/0.5.0_linux_386.zip
    dest=/tmp/serf-0.5.0_linux_386.zip
    sha256sum=9f036ef7243dff4bdc09ff5ad79f4430d72de6c44a710013f1f823000615961c

- name: Install serf
  unarchive: src=/tmp/serf-0.5.0_linux_386.zip dest=/usr/local/bin copy=no

- name: Create serf group
  group: name=serf state=present

- name: Create serf user
  user: name=serf createhome=no group=serf

- name: Install serf upstart script
  copy: src=serf.conf dest=/etc/init/serf.conf owner=root group=root mode=0644

- name: Create serf configuration directory
  file: dest=/etc/serf state=directory owner=root group=root mode=0755

- name: Create serf event handlers directory
  file: dest=/etc/serf/event_handler.d state=directory owner=root group=root mode=0755

- name: Copy serf event handlers
  copy: src={{ item }} dest=/etc/serf/event_handler.d owner=root group=root mode=0755
  with_items:
  - 30-update_hosts.sudo.sh

- name: Setup password-less sudo for event handlers
  copy: src=sudoers.d
        dest=/etc/sudoers.d/serf
        mode=0440
        owner=root
        group=root
        validate="visudo -cf %s"

- name: Create serf event handler
  copy: src=event_handler.sh dest=/etc/serf owner=root group=root mode=0755

- name: Create event handler configuration
  copy: src=50-event_handler.json dest=/etc/serf/50-event_handler.json owner=root group=root mode=0644


