---
- name: Install box-rsync-store
  apt: pkg={{ item }} install_recommends=no
  with_items:
  - rsync

- name: Copy rsync-store upstart conf
  copy: src=rsync-store.conf dest=/etc/init mode=0644 owner=root group=root

- name: Create /data/box directory
  file: path=/data/box state=directory owner=nobody group=nogroup mode=0777

