---
- name: Install box-rsync-store
  apt: pkg={{ item }} install_recommends=no
  with_items:
  - rsync

- name: Copy rsync-store upstart conf
  copy: src=rsync-store.conf dest=/etc/init mode=0644 owner=root group=root

- name: Create /data/box directory
  file:
      path=/data/box
      src=/data/glusterfs/box/brick
      state=link
      owner=nobody
      group=nogroup
      mode=0777

