---
- name: "Install remote-gui"
  apt: pkg={{ item }} install_recommends=no
  with_items:
    - xrdp
    - vnc4server
    - xfonts-base
    - ttf-dejavu
    - rxvt-unicode-256color

- name: "Copy .Xresources"
  copy: src=Xresources dest=/etc/skel/.Xresources

