---
- name: "Install remote-gui"
  apt: pkg={{ item }} install_recommends=no
  with_items:
    - xrdp
    - vnc4server
    - xfonts-base
    - ttf-ubuntu-font-family
    - rxvt-unicode

- name: "Copy X files"
  copy: src={{ item }} dest=/etc/skel/.{{ item }}
  with_items:
  - Xresources
  - xsession

- name: Download solarized Xresources
  get_url:
    url=https://raw.githubusercontent.com/altercation/solarized/master/xresources/solarized
    dest=/etc/skel/.solarized

