---
- hosts: all
  roles:
  - { role: box-common, hostname: BoxGlusterCifsBrick }
  - serf
  tasks:
  - name: Install BoxGlusterCifsBrick
    apt: pkg={{ item }} install_recommends=no
    with_items:
    - glusterfs-server
    - cifs-utils
    - unison

  - name: Create box mount directory
    file: path=/mnt/box state=directory

  - name: Add CIFS share to fstab
    lineinfile:
      insertafter=EOF
      line="//10.0.2.2/box /mnt/box cifs credentials=/etc/samba/box.cifs.credentials"
      dest=/etc/fstab

  - name: Create brick directory
    file: path=/data/glusterfs/cifsvol state=directory

  - name: Create gluster volume
    command: gluster volume create cifsvol BoxGlusterCifsBrick:/data/glusterfs/cifsvol/brick

