---
- name: Set host name
  hostname: name={{ hostname }}

- name: Update hosts file
  lineinfile:
    dest=/etc/hosts
    regexp="^127.0.1.1"
    line="127.0.1.1 {{ hostname }}"
    owner=root
    group=root
    mode=0644

- name: Copy /sbin scripts
  copy: src={{ item }} dest=/sbin/ mode=0755 owner=root group=root
  with_items:
    - mount-box-home.sh
    - box-conf.sh

- name: Copy upstart script for mounting box home
  copy: src=mount-box-home.conf dest=/etc/init mode=0644 owner=root group=root

- name: Create box conf directory
  file: dest=/etc/box state=directory owner=root group=root mode=0755

- name: Set better directory color for ls
  lineinfile: 
    dest={{ item }}
    state=present
    insertafter=EOF
    line='export LS_COLORS="$LS_COLORS:di=01;90:"'
  with_items:
  - /etc/skel/.bashrc
  - /root/.bashrc

