---
- name: Set host name
  hostname: name={{ hostname }}

- name: Update hosts file
  lineinfile:
    dest=/etc/hosts
    regexp="^127.0.1.1"
    line="127.0.1.1 {{ hostname }}"
    owner=root
    group=root
    mode=0644

- name: Copy /sbin scripts
  copy: src={{ item }} dest=/sbin/ mode=0755 owner=root group=root
  with_items:
    - mount-box-home.sh
    - box-conf.sh

- name: Copy upstart script for mounting box home
  copy: src=mount-box-home.conf dest=/etc/init mode=0644 owner=root group=root

- name: Create box conf directory
  file: dest=/etc/box state=directory owner=root group=root mode=0755

- name: Download solarized dircolors
  get_url:
    url=https://raw.githubusercontent.com/seebi/dircolors-solarized/master/dircolors.256dark
    dest=/tmp/dircolors.256dark

- name: Copy solarized dircolors
  copy: src=/tmp/dircolors.256dark dest={{ item }}
  with_items:
  - /etc/skel/.dir_colors
  - /root/.dir_colors

- name: Copy .bashrc
  copy: src=bashrc dest={{ item }}
  with_items:
  - /etc/skel/.bashrc
  - /root/.bashrc


